// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: platform_api.proto

package com.kwai.creative.flutter.channel;

public interface EmptyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:platform.Empty)
    com.google.protobuf.MessageLiteOrBuilder {
}
