// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: flutter_api.proto

package com.kwai.creative.flutter.channel;

public interface FlutterEmptyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:flutter.FlutterEmpty)
    com.google.protobuf.MessageLiteOrBuilder {
}
