// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: flutter_api.proto

package com.kwai.creative.flutter.channel;

public final class KideaFlutterApiChannel {
  private KideaFlutterApiChannel() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
