// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: platform_api.proto

package com.kwai.creative.flutter.channel;

public interface StringValueOrBuilder extends
    // @@protoc_insertion_point(interface_extends:platform.StringValue)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>optional string value = 1;</code>
   */
  java.lang.String getValue();
  /**
   * <code>optional string value = 1;</code>
   */
  com.google.protobuf.ByteString
      getValueBytes();
}
